### ISSUE TITLE
Question about anime streaming

### ISSUE THREAD

**Issue by Niandra8** [meta-boy/Anime-Twist#11]
Hey mate, I just wanted to ask you how do you manage to stream the videos from Twist since I haven't found any API.

**Comment by meta-boy** [comment]
Their web app uses an API for fetching available anime and it's video links, so I just use those. It's there in the source code you can take a look here:

https://github.com/meta-boy/Anime-Twist/blob/d05e3dce1b644e68d367740e2e9a863fc2bd7e19/lib/src/services/anime_twist.dart#L69

**Comment by Niandra8** [comment]
I see, I got to get the anime sources, but you need a password to decrypt them anyway, don't you?

**Comment by meta-boy** [comment]
> I see, I got to get the anime sources, but you need a password to decrypt them anyway, don't you?

Yep, you do need a password. I run this to retrieve the password from my env vars and load it when compiling the app

https://github.com/meta-boy/Anime-Twist/blob/1c0ecbdc83f6839525e09d40b2ec791ccce45145/tools/env.dart#L6

**Comment by Niandra8** [comment]
Did you get I password from them? Do they usually share that with someone developing an app?

**Comment by meta-boy** [comment]
> Did you get I password from them? Do they usually share that with someone developing an app?

Nop, they don't give it out voluntarily but what you can do is reverse engineering the website to get it, it's somewhere in the source code.

That's what I did, rather than website, just decompiled the APK and found out the key.

**Comment by Niandra8** [comment]
I just got it from another project that led it open. Thanks mate!

**Comment by meta-boy** [comment]
Alrighty, closing this one!
