### ISSUE TITLE
Question about building the APK

### ISSUE THREAD

**Issue by dheerajbred** [meta-boy/Anime-Twist#12]
![image](https://user-images.githubusercontent.com/46578244/97785758-05885b00-1bcd-11eb-8015-543aae4d9b05.png)

**Comment by meta-boy** [comment]
If you see in the `tools` directory, you'll find scripts to generate the `env.dart` file. It is used to store the animetwist secret. And is generated during the CI. 
https://github.com/meta-boy/Anime-Twist/blob/1c0ecbdc83f6839525e09d40b2ec791ccce45145/.github/workflows/main.yml#L34

About the `Router` well, the version of flutter you are using has a `Router` class which differs from the `Router` momentum provides. You can follow [this](https://github.com/xamantra/momentum/issues/31) to fix this.

**Comment by meta-boy** [comment]
Welp ig that solves your issue, closing.

**Comment by harsh760** [comment]
@meta-boy Sorry as I'm a beginner in flutter I can not build or test locally due to the .env.dart error. Can you please tell me how to test or build the apk.
Thank you.

**Comment by meta-boy** [comment]
Ask the anime twist developers on their discord to give you the key, run this file https://github.com/meta-boy/Anime-Twist/blob/master/tools/env_from_cli.dart, it will generate the .env.dart file for you

**Comment by meta-boy** [comment]
I guess that answers your question, closing
